### PR TITLE
Fix GLPI cron execution

### LINKED ISSUE #166: cronjob not working
after a clean installation in the newest version, glpi cron.php not working.

The Error Message ist: 
`Database configuration file "/var/www/glpi/config/config_db.php" is missing or is corrupted.
You have to either restart the install process, either restore this file.
GLPI seems to not be configured properly.`

Problem is the phat to config_db.php. 
GLPI is searching in /var/www/glpi/config/ but the config_db.php is in /var/glpi/config
If i set an symbolic link: `lrwxrwxrwx 1 www-data www-data   34 Jul  8 10:28 config_db.php -> ../../../glpi/config/config_db.php` the problem is solved and the glpi cron job is running in the glpi docker container

[GLPI 10.0.18 Copyright (C) 2015-2025 Teclib' and contributors](http://glpi-project.org/)

### PR DESCRIPTION
**Pull request by cedric-anne**
- make env variables available in the cron context
- forward cron logs to the docker logs

fixes #166

### CODE REVIEW

File: glpi/files/opt/startup.sh [hunk 1]
```diff
@@ -76,6 +76,10 @@ do
 done
 
 # Run cron service.
+touch /var/log/cron-output.log
+touch /var/log/cron-errors.log
+tail -F /var/log/cron-output.log &
+tail -F /var/log/cron-errors.log &
```
Comment (cedric-anne) [inline glpi/files/opt/startup.sh:82]: This permit to have this kind of output in docker logs:
image
